# VaR Models

## Step 1: Imports and Data

In [1]:
import numpy as np
import scipy.stats as stats
import pandas as pd
import os
from kaggle.api.kaggle_api_extended import KaggleApi
import zipfile
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objs as go
import simpy
import cvxpy as cp
from arch import arch_model
from statsmodels.tsa.arima.model import ARIMA
import streamlit as st
import datetime
import yfinance as yf

### Kaggle Data

In [2]:
download_dir = "D:\\datasets\\github_financial_time_series_analysis"
api = KaggleApi()
api.authenticate()

dataset = 'andrewmvd/sp-500-stocks'
api.dataset_download_files(dataset, path=download_dir, unzip=True)

files_of_interest = ['sp500_stocks.csv', 'sp500_companies.csv']
for file_name in files_of_interest:
    file_path = os.path.join(download_dir, file_name)
    if os.path.exists(file_path):
        print(f'{file_name} has been downloaded successfully.')
    else:
        print(f'{file_name} is missing.')

Dataset URL: https://www.kaggle.com/datasets/andrewmvd/sp-500-stocks
sp500_stocks.csv has been downloaded successfully.
sp500_companies.csv has been downloaded successfully.

In [3]:
df = pd.read_csv("D:\\datasets\\github_financial_time_series_analysis\\sp500_stocks.csv")
df_sym = pd.read_csv("D:\\datasets\\github_financial_time_series_analysis\\sp500_companies.csv")

In [4]:
df.set_index('Date', inplace=True)

In [5]:
df.sort_index(inplace=True)

In [6]:
df.head()

,Symbol,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,,
2010-01-04,MMM,46.422302,69.414719,69.774246,69.122070,69.473244,3640265.0
2010-01-04,PG,39.663864,61.119999,61.310001,60.630001,61.110001,9190800.0
2010-01-04,AEP,19.709919,34.939999,36.000000,34.799999,35.099998,4076600.0
2010-01-04,VST,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-04,NVDA,0.423988,0.462250,0.465500,0.452750,0.462750,800204000.0

### YFinance Data

In [7]:
df_yf = yf.download('AAPL', period = '1y')

[*********************100%***********************]  1 of 1 completed

In [8]:
df_yf.head()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-08-28,180.089996,180.589996,178.550003,180.190002,179.272659,43820700
2023-08-29,179.699997,184.899994,179.500000,184.119995,183.182617,53003900
2023-08-30,184.940002,187.850006,184.740005,187.649994,186.694656,60813900
2023-08-31,187.839996,189.119995,187.479996,187.869995,186.913544,60794500
2023-09-01,189.490005,189.919998,188.279999,189.460007,188.495468,45732600

## Add columns

In [9]:
df['Return'] = df['Adj Close'].pct_change(fill_method = None) * 100 # Calculate daily returns as percentage
df['Absolute_Return'] = df['Adj Close'].diff()
df['SMA_20'] = df['Adj Close'].rolling(window=20).mean()
df['SMA_200'] = df['Adj Close'].rolling(window=200).mean()
df['EMA_20'] = df['Adj Close'].ewm(span=20, adjust=False).mean()
df['EMA_200'] = df['Adj Close'].ewm(span=200, adjust=False).mean()

# Daily Log Returns
df['Log_Return'] = np.log(df['Adj Close'] / df['Adj Close'].shift(1))

# Volatility (30-day rolling standard deviation of returns)
df['Volatility'] = df['Return'].rolling(window=30).std()

In [10]:
# Relative Strength Index (RSI) - 14-day period
window_length = 14

# Calculate the daily price changes
delta = df['Adj Close'].diff()

# Calculate the gains and losses
gain = (delta.where(delta > 0, 0)).rolling(window=window_length).mean()
loss = (-delta.where(delta < 0, 0)).rolling(window=window_length).mean()

# Calculate the RS and RSI
rs = gain / loss
df['RSI_14'] = 100 - (100 / (1 + rs))

In [11]:
# Bollinger Bands (20-day SMA and 2 standard deviations)
df['Bollinger_Mid'] = df['Adj Close'].rolling(window=20).mean()
df['Bollinger_Upper'] = df['Bollinger_Mid'] + 2 * df['Adj Close'].rolling(window=20).std()
df['Bollinger_Lower'] = df['Bollinger_Mid'] - 2 * df['Adj Close'].rolling(window=20).std()

In [12]:
# MACD (12-day EMA and 26-day EMA)
ema_12 = df['Adj Close'].ewm(span=12, adjust=False).mean()
ema_26 = df['Adj Close'].ewm(span=26, adjust=False).mean()
df['MACD'] = ema_12 - ema_26
df['MACD_Signal'] = df['MACD'].ewm(span=9, adjust=False).mean()
df['MACD_Histogram'] = df['MACD'] - df['MACD_Signal']

In [13]:
# Sharpe Ratio (using a risk-free rate assumption, e.g., 0)
# If you want to use a risk-free rate, adjust accordingly
risk_free_rate = 0
df['Excess_Return'] = df['Return'] - risk_free_rate
df['Sharpe_Ratio'] = df['Excess_Return'].rolling(window=30).mean() / df['Volatility']

In [14]:
df

,Symbol,Adj Close,Close,High,Low,Open,Volume,Return,Absolute_Return,SMA_20,...,Volatility,RSI_14,Bollinger_Mid,Bollinger_Upper,Bollinger_Lower,MACD,MACD_Signal,MACD_Histogram,Excess_Return,Sharpe_Ratio
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,MMM,46.422302,69.414719,69.774246,69.122070,69.473244,3640265.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN
2010-01-04,PG,39.663864,61.119999,61.310001,60.630001,61.110001,9190800.0,-14.558602,-6.758438,NaN,...,NaN,NaN,NaN,NaN,NaN,-0.539135,-0.107827,-0.431308,-14.558602,NaN
2010-01-04,AEP,19.709919,34.939999,36.000000,34.799999,35.099998,4076600.0,-50.307618,-19.953945,NaN,...,NaN,NaN,NaN,NaN,NaN,-2.547157,-0.595693,-1.951464,-50.307618,NaN
2010-01-04,VST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-2.547157,-0.985986,-1.561171,NaN,NaN
2010-01-04,NVDA,0.423988,0.462250,0.465500,0.452750,0.462750,800204000.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-6.336477,-2.056084,-4.280393,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-26,PHM,133.630005,133.630005,136.470001,133.410004,135.250000,1386785.0,116.264772,71.840004,179.763998,...,128.668220,50.296677,179.763998,509.745024,-150.217028,0.961423,15.015697,-14.054275,116.264772,0.354056
2024-08-26,CFG,42.709999,42.709999,43.285000,42.660000,43.169998,2756191.0,-68.038616,-90.920006,177.847498,...,130.274945,45.246918,177.847498,510.675707,-154.980711,-9.844834,10.043591,-19.888425,-68.038616,0.316391
2024-08-26,PSA,339.660004,339.660004,342.989990,338.720001,342.540009,420934.0,695.270454,296.950005,184.408998,...,174.818622,54.270513,184.408998,524.862678,-156.044681,5.489237,9.132720,-3.643483,695.270454,0.382907
2024-08-26,QCOM,169.490005,169.490005,172.380005,168.529999,172.009995,7211342.0,-50.100099,-170.169998,184.085999,...,175.998975,51.233461,184.085999,524.585723,-156.413726,3.865740,8.079324,-4.213584,-50.100099,0.352306
2024-08-26,ZTS,181.559998,181.559998,182.589996,180.520096,181.039993,992261.0,7.121359,12.069992,185.407999,...,174.791714,50.193951,185.407999,525.639404,-154.823406,3.512564,7.165972,-3.653408,7.121359,0.367737

### add 'sector' and 'industry' columns from other dataset

In [15]:
df.head()

,Symbol,Adj Close,Close,High,Low,Open,Volume,Return,Absolute_Return,SMA_20,...,Volatility,RSI_14,Bollinger_Mid,Bollinger_Upper,Bollinger_Lower,MACD,MACD_Signal,MACD_Histogram,Excess_Return,Sharpe_Ratio
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,MMM,46.422302,69.414719,69.774246,69.122070,69.473244,3640265.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN
2010-01-04,PG,39.663864,61.119999,61.310001,60.630001,61.110001,9190800.0,-14.558602,-6.758438,NaN,...,NaN,NaN,NaN,NaN,NaN,-0.539135,-0.107827,-0.431308,-14.558602,NaN
2010-01-04,AEP,19.709919,34.939999,36.000000,34.799999,35.099998,4076600.0,-50.307618,-19.953945,NaN,...,NaN,NaN,NaN,NaN,NaN,-2.547157,-0.595693,-1.951464,-50.307618,NaN
2010-01-04,VST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-2.547157,-0.985986,-1.561171,NaN,NaN
2010-01-04,NVDA,0.423988,0.462250,0.465500,0.452750,0.462750,800204000.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-6.336477,-2.056084,-4.280393,NaN,NaN

In [16]:
df_sym.head()

,Exchange,Symbol,Shortname,Longname,Sector,Industry,Currentprice,Marketcap,Ebitda,Revenuegrowth,City,State,Country,Fulltimeemployees,Longbusinesssummary,Weight
0,NMS,AAPL,Apple Inc.,Apple Inc.,Technology,Consumer Electronics,227.18,3454067277824,1.317810e+11,0.049,Cupertino,CA,United States,161000.0,"Apple Inc. designs, manufactures, and markets ...",0.066196
1,NMS,NVDA,NVIDIA Corporation,NVIDIA Corporation,Technology,Semiconductors,126.46,3110701105152,4.927500e+10,2.621,Santa Clara,CA,United States,29600.0,NVIDIA Corporation provides graphics and compu...,0.059616
2,NMS,MSFT,Microsoft Corporation,Microsoft Corporation,Technology,Software - Infrastructure,413.49,3073487667200,1.294330e+11,0.152,Redmond,WA,United States,228000.0,Microsoft Corporation develops and supports so...,0.058903
3,NMS,GOOGL,Alphabet Inc.,Alphabet Inc.,Communication Services,Internet Content & Information,166.16,2055565475840,1.154780e+11,0.136,Mountain View,CA,United States,179582.0,Alphabet Inc. offers various products and plat...,0.039394
4,NMS,GOOG,Alphabet Inc.,Alphabet Inc.,Communication Services,Internet Content & Information,167.93,2055009599488,1.154780e+11,0.136,Mountain View,CA,United States,179582.0,Alphabet Inc. offers various products and plat...,0.039384

In [17]:
# Assuming df2 has one row with 'symbol', 'sector', and 'industry' columns
df['sector'] = df_sym['Sector'].iloc[0]
df['industry'] = df_sym['Industry'].iloc[0]

In [18]:
df

,Symbol,Adj Close,Close,High,Low,Open,Volume,Return,Absolute_Return,SMA_20,...,Bollinger_Mid,Bollinger_Upper,Bollinger_Lower,MACD,MACD_Signal,MACD_Histogram,Excess_Return,Sharpe_Ratio,sector,industry
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,MMM,46.422302,69.414719,69.774246,69.122070,69.473244,3640265.0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,Technology,Consumer Electronics
2010-01-04,PG,39.663864,61.119999,61.310001,60.630001,61.110001,9190800.0,-14.558602,-6.758438,NaN,...,NaN,NaN,NaN,-0.539135,-0.107827,-0.431308,-14.558602,NaN,Technology,Consumer Electronics
2010-01-04,AEP,19.709919,34.939999,36.000000,34.799999,35.099998,4076600.0,-50.307618,-19.953945,NaN,...,NaN,NaN,NaN,-2.547157,-0.595693,-1.951464,-50.307618,NaN,Technology,Consumer Electronics
2010-01-04,VST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-2.547157,-0.985986,-1.561171,NaN,NaN,Technology,Consumer Electronics
2010-01-04,NVDA,0.423988,0.462250,0.465500,0.452750,0.462750,800204000.0,NaN,NaN,NaN,...,NaN,NaN,NaN,-6.336477,-2.056084,-4.280393,NaN,NaN,Technology,Consumer Electronics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-26,PHM,133.630005,133.630005,136.470001,133.410004,135.250000,1386785.0,116.264772,71.840004,179.763998,...,179.763998,509.745024,-150.217028,0.961423,15.015697,-14.054275,116.264772,0.354056,Technology,Consumer Electronics
2024-08-26,CFG,42.709999,42.709999,43.285000,42.660000,43.169998,2756191.0,-68.038616,-90.920006,177.847498,...,177.847498,510.675707,-154.980711,-9.844834,10.043591,-19.888425,-68.038616,0.316391,Technology,Consumer Electronics
2024-08-26,PSA,339.660004,339.660004,342.989990,338.720001,342.540009,420934.0,695.270454,296.950005,184.408998,...,184.408998,524.862678,-156.044681,5.489237,9.132720,-3.643483,695.270454,0.382907,Technology,Consumer Electronics
2024-08-26,QCOM,169.490005,169.490005,172.380005,168.529999,172.009995,7211342.0,-50.100099,-170.169998,184.085999,...,184.085999,524.585723,-156.413726,3.865740,8.079324,-4.213584,-50.100099,0.352306,Technology,Consumer Electronics
2024-08-26,ZTS,181.559998,181.559998,182.589996,180.520096,181.039993,992261.0,7.121359,12.069992,185.407999,...,185.407999,525.639404,-154.823406,3.512564,7.165972,-3.653408,7.121359,0.367737,Technology,Consumer Electronics

In [19]:
df['Market_Cap'] = df['Adj Close'] * df['Volume']

In [35]:
"""# Function to get dividend yield
def get_dividend_yield(symbol):
    try:
        ticker = yf.Ticker(symbol)
        info = ticker.info
        return info.get('dividendYield', 'N/A')  # Return dividend yield or 'N/A' if not available
    except Exception as e:
        print(f"Error fetching data for {symbol}: {e}")
        return 'N/A'

# Create a list to hold the dividend yield values
dividend_yields = [get_dividend_yield(symbol) for symbol in df['Symbol']]"""

'# Function to get dividend yield\ndef get_dividend_yield(symbol):\n    try:\n        ticker = yf.Ticker(symbol)\n        info = ticker.info\n        return info.get(\'dividendYield\', \'N/A\')  # Return dividend yield or \'N/A\' if not available\n    except Exception as e:\n        print(f"Error fetching data for {symbol}: {e}")\n        return \'N/A\'\n\n# Create a list to hold the dividend yield values\ndividend_yields = [get_dividend_yield(symbol) for symbol in df[\'Symbol\']]'

In [20]:
df.tail()

,Symbol,Adj Close,Close,High,Low,Open,Volume,Return,Absolute_Return,SMA_20,...,Bollinger_Upper,Bollinger_Lower,MACD,MACD_Signal,MACD_Histogram,Excess_Return,Sharpe_Ratio,sector,industry,Market_Cap
Date,,,,,,,,,,,,,,,,,,,,,
2024-08-26,PHM,133.630005,133.630005,136.470001,133.410004,135.250000,1386785.0,116.264772,71.840004,179.763998,...,509.745024,-150.217028,0.961423,15.015697,-14.054275,116.264772,0.354056,Technology,Consumer Electronics,1.853161e+08
2024-08-26,CFG,42.709999,42.709999,43.285000,42.660000,43.169998,2756191.0,-68.038616,-90.920006,177.847498,...,510.675707,-154.980711,-9.844834,10.043591,-19.888425,-68.038616,0.316391,Technology,Consumer Electronics,1.177169e+08
2024-08-26,PSA,339.660004,339.660004,342.989990,338.720001,342.540009,420934.0,695.270454,296.950005,184.408998,...,524.862678,-156.044681,5.489237,9.132720,-3.643483,695.270454,0.382907,Technology,Consumer Electronics,1.429744e+08
2024-08-26,QCOM,169.490005,169.490005,172.380005,168.529999,172.009995,7211342.0,-50.100099,-170.169998,184.085999,...,524.585723,-156.413726,3.865740,8.079324,-4.213584,-50.100099,0.352306,Technology,Consumer Electronics,1.222250e+09
2024-08-26,ZTS,181.559998,181.559998,182.589996,180.520096,181.039993,992261.0,7.121359,12.069992,185.407999,...,525.639404,-154.823406,3.512564,7.165972,-3.653408,7.121359,0.367737,Technology,Consumer Electronics,1.801549e+08

## Step 2: VaR Models

In [37]:
def calculate_var_variance_covariance(returns, confidence_level=0.95):
    mean = np.mean(returns)
    std_dev = np.std(returns)
    z_score = stats.norm.ppf(1 - confidence_level)
    var = mean + z_score * std_dev
    return var

In [38]:
def calculate_var_historical(returns, confidence_level=0.95):
    sorted_returns = np.sort(returns)
    index = int((1 - confidence_level) * len(sorted_returns))
    var = -sorted_returns[index]  # Negative sign because VaR is a loss
    return var

In [39]:
def calculate_var_monte_carlo(returns, confidence_level=0.95, num_simulations=10_000):
    mean = np.mean(returns)
    std_dev = np.std(returns)
    simulated_returns = np.random.normal(mean, std_dev, num_simulations)
    sorted_simulations = np.sort(simulated_returns)
    index = int((1 - confidence_level) * num_simulations)
    var = -sorted_simulations[index]
    return var

In [40]:
historical_returns = np.random.normal(0, 0.02, 1000)  # Simulated returns
var_variance_covariance = calculate_var_variance_covariance(historical_returns)
var_historical = calculate_var_historical(historical_returns)
var_monte_carlo = calculate_var_monte_carlo(historical_returns)

In [41]:
print(f"Variance-Covariance VaR (95% confidence level): {var_variance_covariance}")
print(f"Historical VaR (95% confidence level): {var_historical}")
print(f"Monte Carlo VaR (95% confidence level): {var_monte_carlo}")

Variance-Covariance VaR (95% confidence level): -0.03076113877404623
Historical VaR (95% confidence level): 0.03067093832921509
Monte Carlo VaR (95% confidence level): 0.03036743112476105

## Step 3. Advanced Risk Models

In [42]:
def calculate_multifactor_var(returns, macro_factors, confidence_level=0.95):
    from sklearn.linear_model import LinearRegression
    X = macro_factors
    y = returns
    model = LinearRegression().fit(X, y)
    predicted_returns = model.predict(X)
    std_dev = np.std(predicted_returns)
    z_score = stats.norm.ppf(1 - confidence_level)
    var = -np.mean(predicted_returns) + z_score * std_dev
    return var

In [43]:
def calculate_garch_var(returns, confidence_level=0.95):
    garch_model = arch_model(returns, vol='Garch', p=1, q=1)
    garch_fit = garch_model.fit(disp="off")
    forecast = garch_fit.forecast(horizon=1)
    vol_forecast = forecast.variance.values[-1, :]
    std_dev = np.sqrt(vol_forecast)
    z_score = stats.norm.ppf(1 - confidence_level)
    var = -np.mean(returns) + z_score * std_dev
    return var

In [44]:
garch_var = calculate_garch_var(historical_returns)

C:\Users\blake\Documents\github\finance_time_series\venv\Lib\site-packages\arch\univariate\base.py:311: DataScaleWarning: y is poorly scaled, which may affect convergence of the optimizer when
estimating the model parameters. The scale of y is 0.0003758. Parameter
estimation work better when this value is between 1 and 1000. The recommended
rescaling is 100 * y.

This warning can be disabled by either rescaling y before initializing the
model or by setting rescale=False.

  warnings.warn(

## 4. Backtesting and Portfolio Optimization

In [45]:
def backtest_var(returns, var_values, confidence_level=0.95):
    exceedances = returns < -var_values
    hit_rate = exceedances.sum() / len(exceedances)
    expected_exceedance_rate = 1 - confidence_level
    backtest_result = {
        'Actual Exceedance Rate': hit_rate,
        'Expected Exceedance Rate': expected_exceedance_rate
    }
    return backtest_result

In [46]:
backtest_results = backtest_var(historical_returns, var_historical)
print(backtest_results)

{'Actual Exceedance Rate': 0.05, 'Expected Exceedance Rate': 0.050000000000000044}

In [54]:
# Select only the numeric columns
numeric_data = df.select_dtypes(include=[np.number])

In [60]:
expected_returns = numeric_data.pct_change().mean().values()  # Assuming percentage returns

C:\Users\blake\AppData\Local\Temp\ipykernel_13980\1649550583.py:1: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  expected_returns = numeric_data.pct_change().mean().values()  # Assuming percentage returns

TypeError: 'numpy.ndarray' object is not callable

In [51]:
def mean_variance_optimization(expected_returns, cov_matrix, risk_free_rate=0.01):
    n = len(expected_returns)
    weights = cp.Variable(n)
    portfolio_return = expected_returns @ weights
    portfolio_volatility = cp.quad_form(weights, cov_matrix)
    problem = cp.Problem(cp.Maximize(portfolio_return - risk_free_rate * cp.norm(weights, 1)),
                         [cp.sum(weights) == 1, weights >= 0])
    problem.solve()
    return weights.value

SyntaxError: invalid syntax (4152713572.py, line 1)

In [48]:
optimal_weights = mean_variance_optimization(expected_returns, covariance_matrix)

NameError: name 'expected_returns' is not defined

## 5. Stress Testing

In [69]:
def market_crash(env, portfolio_value):
    while True:
        yield env.timeout(100)
        crash_impact = np.random.uniform(-0.3, -0.5)
        portfolio_value *= (1 + crash_impact)
        print(f"Market crash! New portfolio value: {portfolio_value}")

In [70]:
def interest_rate_spike(env, portfolio_value):
    while True:
        yield env.timeout(200)
        spike_impact = np.random.uniform(-0.1, -0.2)
        portfolio_value *= (1 + spike_impact)
        print(f"Interest rate spike! New portfolio value: ${portfolio_value:,.0f}")

In [71]:
def stress_test_simulation():
    env = simpy.Environment()
    portfolio_value = 100000
    env.process(market_crash(env, portfolio_value))
    env.process(interest_rate_spike(env, portfolio_value))
    env.run(until=500)

In [72]:
stress_test_simulation()

Market crash! New portfolio value: 55368.13200288291
Interest rate spike! New portfolio value: $85,170
Market crash! New portfolio value: 36878.264848546205
Market crash! New portfolio value: 25555.032640267476
Interest rate spike! New portfolio value: $68,565
Market crash! New portfolio value: 17725.424966878156

## Time Series Forecasting

In [73]:
def forecast_arima(returns, order=(1, 1, 1)):
    model = ARIMA(returns, order=order)
    fit = model.fit()
    forecast = fit.forecast(steps=10)
    return forecast

In [74]:
arima_forecast = forecast_arima(historical_returns)

In [75]:
arima_forecast

array([0.0012673 , 0.0016047 , 0.00161085, 0.00161097, 0.00161097,
       0.00161097, 0.00161097, 0.00161097, 0.00161097, 0.00161097])